server:
  port: '8082'

spring:
  datasource:
    username: playground
    url: jdbc:postgresql://localhost:5432/playground
    driverClassName: org.postgresql.Driver
    password: password
  jpa:
    hibernate:
      database: postgresql
      ddl-auto: create-drop
    show-sql: 'true'
    properties:
      hibernate:
        format_sql: 'true'
    database-platform: org.hibernate.dialect.PostgreSQLDialect
